---
- name: Create org and repos
  gather_facts: no
  ignore_errors: yes
  hosts: localhost
  vars:
    ansible_remote_tmp: /runner/.ansible/tmp

    quay_route: http://registry-quay-app

    quay_user_password: openshift

  tasks:

    - name: Create users
      herve4m.quay.quay_user:
        username: "user{{ item }}"
        email: "user{{ item }}@workshop-noreply.com"
        quay_host: "{{ quay_route }}"
        quay_token: "{{ access_token }}"
        state: present
      with_sequence: 0-{{ users }}

    - name: create organizations
      herve4m.quay.quay_organization:
        name: "org-user{{ item }}"
        email: "org-user{{ item }}@workshop-noreply.com"
        time_machine_expiration: "14d"
        state: present
        quay_host: "{{ quay_route }}"
        quay_token: "{{ access_token }}"
      with_sequence: 0-{{ users }}

    - name: Create teams
      herve4m.quay.quay_team:
        name: "team-user{{ item }}"
        organization: "org-user{{ item }}"
        description: "user{{ item }} team"
        role: "creator"
        members:
          - user{{ item }}
        append: false
        state: present
        quay_host: "{{ quay_route }}"
        quay_token: "{{ access_token }}"
      with_sequence: 0-{{ users }}

    # Update later once we figure out what image repos are needed
    - name: create test repositories
      herve4m.quay.quay_repository:
        name: "user{{ item }}/test"
        visibility: private
        description: "Test Repository"
        perms:
          - name: user{{ item }}
            type: team
            role: admin
        state: present
        quay_host: "{{ quay_route }}"
        quay_token: "{{ access_token }}"
        visibility: "public"
      with_sequence: 0-{{ users }}

    - name: Set flag
      set_fact: flag = failed
      when: "'FAILED' in command_result.stderr"
