# Generate robot accounts
- debug:
    msg: "***** Creating robot token secret for user{{ user }} *****"

- name: Check if secret already exists
  set_fact:
    quay_secret: "{{ query('kubernetes.core.k8s', kind='Secret', namespace='user'~user, resource_name='quay') }}"

- name: Create robot account
  herve4m.quay.quay_robot:
    name: workshop{{ user }}+pipeline
    description: Robot account for workshop{{ user }}
    state: present
    quay_host: "{{ quay_route }}"
    quay_token: "{{ access_token }}"
  register: robot_details
  when: quay_secret is undefined

- name: Create auth
  set_fact:
    auth: "{{ 'user' ~ user ~ ':' ~ robot_details.token | b64encode }}"
  when: quay_secret is undefined

- name: Create dockerconfig
  set_fact:
    dockerconfigjson: "{{ lookup('template', '.dockerconfigjson.j2') }}"
  when: quay_secret is undefined

- name: Store secret in cicd namespace
  k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: quay
        namespace: "user{{ user }}-cicd"
      data:
        .dockerconfigjson: "{{ dockerconfigjson | b64encode }}"
      type: kubernetes.io/dockerconfigjson
  when: quay_secret is undefined
