# Generate robot accounts
- debug:
    msg: "***** Creating robot token secret for user{{ user }} *****"

- name: Check if secret already exists
  set_fact:
    quay_secret: "{{ query('kubernetes.core.k8s', kind='Secret', namespace='user'~user, resource_name='quay') }}"

- name: Create robot account
  herve4m.quay.quay_robot:
    name: workshop{{ user }}+pipeline
    description: Robot account for workshop{{ user }}
    state: present
    quay_host: "{{ quay_route }}"
    quay_token: "{{ access_token }}"
  register: robot_details
  when: quay_secret is undefined

- name: Create pull secret
  shell: oc create secret -n user{{ user }}-cicd docker-registry quay --docker-server=registry-quay-quay-operator.{{ sub_domain }} --docker-username="workshop{{ user }}+pipeline" --docker-password={{ robot_details.token }}
